language: python
cache: pip

python:
 - 3.6
 - 3.7
 - 3.8

install:
 - pip install pycodestyle pyflakes
 - pip install -r requirements.txt
 - npm install svgexport -g

script:
 # Unit tests
 - python test_utils.py

 # Static analysis
 - flake8

 # Test run
 - ./build.sh

matrix:
  fast_finish: true
