language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - 2.7
 - 3.6

sudo: false

install:
 - pip install pep8 pyflakes
 - pip install -r requirements.txt
 - npm install svgexport -g

script:
 # Unit tests
 - python test_utils.py

 # Static analysis
 - pyflakes .
 - pep8 --statistics --count .

 # Test run
 - python generate.py

matrix:
  fast_finish: true
