language: python
cache: pip
dist: xenial

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - 3.6
 - 3.7
 - 3.8-dev

install:
 - pip install pycodestyle pyflakes
 - pip install -r requirements.txt
 - npm install svgexport -g

script:
 # Unit tests
 - python test_utils.py

 # Static analysis
 - pyflakes .
 - pycodestyle .

 # Test run
 - ./build.sh

matrix:
  fast_finish: true
