language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - 2.7
 - 3.6

sudo: false

install:
 - pip install pep8 pyflakes

script:
 # Static analysis
 - pyflakes .
 - pep8 --statistics --count .

 # Test run
 - python generate.py

matrix:
  fast_finish: true
